### ISSUE TITLE
Update the depency com.taoensso/sente

### ISSUE THREAD

**Issue by davidpham87** [flexsurfer/re-frisk-remote#13]
Hello,

I tried to install this library, but the version of `com.taoensso/sente` fails to load as it misses the `websocket`. I tried to upgrade it but it fails.

Best regards,
David

**Comment by adrielsantiago** [comment]
Bump! Would be nice to at least bump the version to v. 1.13.1 since v. 1.14 introduces a breaking change that would require https://github.com/flexsurfer/lein-re-frisk to be updated as well. Getting all the way up to date would be great though. Looks like the api change is minimal.

**Comment by flexsurfer** [comment]
fixed in 0.5.10

**Comment by flexsurfer** [comment]
for websocket see this library https://github.com/flexsurfer/re-frisk-rn
