### ISSUE TITLE
Make optimizations in transferred data

### ISSUE THREAD

**Issue by flexsurfer** [flexsurfer/re-frisk-remote#3]
In current implementation all data is sending each time app-db or subscriptions are changed, we need to optimize it and send only difference because data transformation is expensive

https://github.com/flexsurfer/re-frisk-remote/blob/master/src/re_frisk_remote/core.cljs#L27
https://github.com/flexsurfer/re-frisk-remote/blob/master/src/re_frisk_remote/core.cljs#L37

And also implement update debouncing for app-db, in current implementation it works only for subscriptions

This task should be done with https://github.com/flexsurfer/lein-re-frisk/issues/4

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x548fdb5f4d286c35350f4afa14466e847613b656d0bbe8c70f9e6e4c727757f8](https://etherscan.io/tx/0x548fdb5f4d286c35350f4afa14466e847613b656d0bbe8c70f9e6e4c727757f8)

**Comment by dottedmag** [comment]
I'll take care of this one.

**Comment by qnnguyen17** [comment]
Hi, I'd like to work on this if you are still looking for a contributor. Is there anything in particular I should know before getting started?

**Comment by poiga** [comment]
I am working on this.

**Comment by dottedmag** [comment]
@poiga I've got nearly finished version of this thing (going to finish today), but apparently forgot to comment on this issue.

**Comment by poiga** [comment]
@dottedmag that's too bad. I have been debugging it for few days as well and have progress. 
I hate such collisions...
What to do now?

**Comment by poiga** [comment]
@dottedmag , but if you say you have it nearly finished then go on...

**Comment by poiga** [comment]
@dottedmag I thought you are working on this one https://github.com/status-im/status-react/issues/1048

**Comment by dottedmag** [comment]
@poiga I did, but got stuck on setup, updated the comment there.

**Comment by dottedmag** [comment]
@flexsurfer Done, please have a look. I haven't bumped version numbers anywhere this time.

**Comment by flexsurfer** [comment]
yes @dottedmag thanks for reminding, sorry for the delay

**Comment by dottedmag** [comment]
@flexsurfer Added changes here and in `lein-re-frisk` to only compute diffs and send messages if there is a UI client connected to sidecar.

**Comment by dottedmag** [comment]
@flexsurfer Problem with `:app-db` transfers is fixed. Scenario for reproducing:
1. open the `re-frisk-remote`
2. open the UI
3. close the UI
4. wait for a few seconds (so that `lein-re-frisk` detects the disconnection)
5. open the UI again
6. See no `:app-db` anymore.

**Comment by dottedmag** [comment]
@flexsurfer `:before`/`:after` mixup is fixed.

Both fixes are added as separate commits to the pull request for easier review.

**Comment by flexsurfer** [comment]
Awesome job @dottedmag , thanks!
